import type { ArchivesContent } from "./types"

export const archivesContent: ArchivesContent = {
  books: [
    {
      id: "book-1",
      title: "The History of Grace Community Church",
      description: "A comprehensive look at our church's founding and growth over the decades.",
      date: "2020-01-15",
      author: "Pastor John Mitchell",
      pages: 156,
      isbn: "978-1234567890",
      url: "/archives/books/church-history.pdf",
      thumbnail: "/placeholder.svg?height=200&width=150",
    },
    {
      id: "book-2",
      title: "Faith in Action: Community Service Guide",
      description: "Practical guide for organizing and participating in community outreach programs.",
      date: "2021-06-10",
      author: "Maria Rodriguez",
      pages: 89,
      isbn: "978-0987654321",
      url: "/archives/books/faith-in-action.pdf",
      thumbnail: "/placeholder.svg?height=200&width=150",
    },
    {
      id: "book-3",
      title: "Worship Through the Seasons",
      description: "A collection of liturgies and worship resources for the church year.",
      date: "2022-03-20",
      author: "David Chen",
      pages: 234,
      isbn: "978-1122334455",
      url: "/archives/books/worship-seasons.pdf",
      thumbnail: "/placeholder.svg?height=200&width=150",
    },
  ],
  journals: [
    {
      id: "journal-1",
      title: "Grace Community Quarterly - Spring 2024",
      description: "Latest news, testimonies, and updates from our church community.",
      date: "2024-03-01",
      issue: "Spring 2024",
      volume: "Vol. 39",
      url: "/archives/journals/spring-2024.pdf",
      thumbnail: "https://i.pinimg.com/736x/76/7d/58/767d5879cc2a5abb470f74496b429248.jpg",
    },
    {
      id: "journal-2",
      title: "Grace Community Quarterly - Winter 2024",
      description: "Year-end reflections, Christmas celebrations, and ministry highlights.",
      date: "2023-12-01",
      issue: "Winter 2024",
      volume: "Vol. 38",
      url: "/archives/journals/winter-2024.pdf",
      thumbnail: "https://i.pinimg.com/736x/a6/e9/6f/a6e96f2f887d21e0e6fa2e1bdfc3c745.jpg",
    },
    {
      id: "journal-3",
      title: "Grace Community Quarterly - Fall 2023",
      description: "Harvest festival coverage, new member spotlights, and upcoming events.",
      date: "2023-09-01",
      issue: "Fall 2023",
      volume: "Vol. 38",
      url: "/archives/journals/fall-2023.pdf",
      thumbnail: "https://i.pinimg.com/736x/17/6f/bb/176fbbaad2aa60f2140b0b11b0c1de05.jpg",
    },
  ],
  churchVideos: [
    {
      id: "video-1",
      title: "Easter Sunday Service 2024",
      description: "Complete recording of our Easter celebration service with special music and message.",
      date: "2024-03-31",
      duration: "1:15:30",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
    {
      id: "video-2",
      title: "Christmas Eve Candlelight Service 2023",
      description: "Beautiful candlelight service with carols and the Christmas story.",
      date: "2023-12-24",
      duration: "45:20",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
    {
      id: "video-3",
      title: "Church Anniversary Celebration",
      description: "Celebrating 38 years of ministry with testimonies and special presentations.",
      date: "2023-10-15",
      duration: "2:10:45",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
  ],
  churchPictures: [
    {
      id: "pic-1",
      title: "Easter Sunday 2024",
      description: "Photos from our Easter celebration including baptisms and fellowship.",
      date: "2024-03-31",
      imageUrl: "/placeholder.svg?height=300&width=400",
      photographer: "Sarah Johnson",
    },
    {
      id: "pic-2",
      title: "Youth Summer Camp 2023",
      description: "Memories from our annual youth summer camp at Pine Lake.",
      date: "2023-07-15",
      imageUrl: "/placeholder.svg?height=300&width=400",
      photographer: "Mike Thompson",
    },
    {
      id: "pic-3",
      title: "Community Food Drive",
      description: "Volunteers organizing and distributing food to families in need.",
      date: "2023-11-20",
      imageUrl: "/placeholder.svg?height=300&width=400",
      photographer: "Lisa Chen",
    },
  ],
  ngoVideos: [
    {
      id: "ngo-1",
      title: "Mission Trip to Guatemala 2023",
      description: "Documentary of our mission team's work building homes and serving communities.",
      date: "2023-08-10",
      duration: "28:15",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
    {
      id: "ngo-2",
      title: "Local Homeless Shelter Partnership",
      description: "Ongoing partnership with downtown shelter providing meals and support.",
      date: "2023-12-05",
      duration: "15:45",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
    {
      id: "ngo-3",
      title: "Disaster Relief Efforts",
      description: "Church response to recent natural disasters with relief supplies and volunteers.",
      date: "2023-09-20",
      duration: "22:30",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/placeholder.svg?height=180&width=320",
    },
  ],
}
